import json
import os
from Graph.state import CVEClassifierState

class StateFromFileLoader:
    """
    A LangGraph node that loads partial CVE state from a pre-existing JSON log file.

    This node acts as a static data provider, replacing the fetching, scraping, 
    and processing steps (NVD, Trafilatura, Chunking, Filtering) during testing.
    It reads a log file generated by a previous run and populates the pipeline state 
    with the requested fields for the specific CVE ID.

    Attributes:
        log_data (dict): The entire content of the JSON log file loaded into memory.
        fields_to_load (list[str]): A list of state keys to extract from the log 
            and inject into the pipeline state.
    """

    def __init__(self, file_path: str, fields_to_load: list[str] = ["nvd_description", "nvd_filtered_chunks"]):
        """
        Initializes the loader by reading and parsing the JSON log file.

        Args:
            file_path (str): The absolute or relative path to the JSON log file.
            fields_to_load (list[str]): The specific fields to retrieve from the 
                log entry (e.g., ['nvd_description', 'nvd_filtered_chunks']).
                Defaults to loading description and filtered chunks if None.

        Raises:
            FileNotFoundError: If the specified file_path does not exist.
            ValueError: If the JSON file is malformed.
        """
        if not os.path.exists(file_path):
            raise FileNotFoundError(f" The log file at {file_path} was not found.")

        print(f"Loading static state from: {file_path}")
        
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                self.log_data = json.load(f)
        except json.JSONDecodeError as e:
            raise ValueError(f"Failed to parse JSON log file: {e}")

        # Default fields if none provided
        self.fields_to_load = fields_to_load

    def __call__(self, state: CVEClassifierState) -> CVEClassifierState:
        """
        Retrieves data for the current CVE ID from the loaded log and updates the state.

        Args:
            state (CVEClassifierState): The current pipeline state containing 'cve_id'.

        Returns:
            CVEClassifierState: The state updated with the pre-computed fields found in the log.
            If the CVE is not found or has no data, the state remains unchanged (or partially updated).
        """
        cve_id = state.get("cve_id")
        
        # Access the 'cves' dictionary inside the log structure
        cves_data = self.log_data.get("cves", {})
        
        if cve_id not in cves_data:
            print(f"Warning: CVE {cve_id} not found in the log file.")
            return state

        cve_entry = cves_data[cve_id]
        
        # Check if the previous run for this CVE was successful
        if cve_entry.get("status") == "error":
            print(f"Warning: Log entry for {cve_id} indicates a previous error.")
            return state

        updates = {}
        for field in self.fields_to_load:
            if field in cve_entry:
                updates[field] = cve_entry[field]
        
        print(f"Loaded static context for {cve_id}")
        
        return {**state, **updates}